package com.example.easyTest.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class QuestionTest {
    @Id
    private UUID id = UUID.randomUUID(); // Autogenerated UUID
    private String question;
    private List<String> answer;
    private int level;
    private int solution;
}
